---
title: "visualize_WARM-USEEIO"
output: html_notebook
---

## `renv` testing
```{r}
# install.packages("renv")  # install latest renv release into root env

## Lockfile creation
# renv::activate()
# renv::install('remotes')
# remotes::install_github("USEPA/useeior@hybridization")
  # try useeior:::printValidationResults(model) or useeior:::hybridizeAMatrix to check for correct install
# renv::snapshot(lockfile="WARM-USEEIO.lock")

## Populate an empty env w/ packages from existing lockfile
# renv::activate()
# renv::restore(lockfile="WARM-USEEIO.lock")

## Status checks
# renv::status(lockfile = "WARM-USEEIO.lock")
# pkgs <- as.data.frame(installed.packages())
# .libPaths()

## Upadate useeior to latest commit: overwrite RemoteSha & delete Hash in lockfile
# renv::purge("useeior")  # purge old copy from cache
# renv::remove("useeior")
# remotes::install_github("USEPA/useeior@WIO")  # reinstall
# renv::snapshot(lockfile="WARM-USEEIO.lock")  # update the lockfile

## Wipe current renv & purge pkg cache
# renv::deactivate()
# renv::purge(".")  # purge all packages from cache
```


## Build the hybrid model
```{r}
library('useeior')
# devtools::load_all("./renv/library/R-4.1/x86_64-w64-mingw32/useeior")

# Build model from specs
# TODO: alter this to point to HIO/useeior/
configpaths <- file.path("data", "m1", c("USEEIO-WARM.yml",
                                   "WARMv15.yml"))
modelname <- "USEEIO-WARM"
model <- buildModel(modelname, configpaths)
```


## Tidy and manipulate
```{r, include=FALSE}
source("DataVisFunctions.R")

# choose impact (from model$Indicators$meta$Name) to visualize
# WARMv15 impacts available: {"Greenhouse Gases", "Wages", "Taxes", "Jobs Supported"}
impact_vis = "Jobs Supported"

# import WARM results
df_warm <- read.csv(file.path("data", "WARM_cntrb_results.csv")) %>% 
  dplyr::filter(impact == impact_vis) %>%   # filter by impact
  dplyr::select(-impact)                    # then drop impact col

df_A <- useeior:::disaggregateTotalToDirectAndTier1(model, impact_vis) %>%
  dplyr::filter(sector_code %in% model$HybridizationSpecs$Processes$Code_Loc,
                impact_per_purchase != 0) %>% # keep WARM sectors & their non-0 purchases
  tibble::add_column(source = modelname) %>%
  dplyr::bind_rows(., df_warm) %>%            # merge in WARM results
  labelSectorPathwaysAndMaterials()


# # total sector impacts per purchase, ordered
# sector_order <- c(
#  "Anaerobic digestion of Food Waste; Dry digestion, Cured",
#  "MSW composting of Food Waste",
#  "MSW combustion of Food Waste",
#  "MSW landfilling of Food Waste; National average LFG recovery, typical collection, National average conditions",
#  "MSW recycling of Concrete",
#  "MSW landfilling of Concrete")
# 
# df_A_summ <- df_A %>% 
#   dplyr::group_by(source, sector, sector_code) %>%
#   dplyr::summarise(total = sum(impact_per_purchase), .groups="drop") %>%
#   dplyr::arrange(desc(source), match(sector, sector_order)) %>% 
#   write.csv(file.path("output", glue::glue("{modelname}_{impact_vis}.csv")))
```


## Preliminary bar plot
```{r, fig.height = 6, fig.width = 12}
# manually specify legend order & legend item linebreak (wrap) position
legend_order <- c("Direct", "Gasoline, fuels, and by-products of petroleum refining",
                  "Electricity", "Truck transport", "Ready-mix concrete", 
                  "Ready-mix concrete, recycled", "Ready-mix concrete, virgin")

legend_wrap <- unique(df_A$purchased_commodity) %>% 
  setNames(sub("((?<=, and)\\s)|((?<=,)\\s(?!and))(?!.*,)", "\n", ., perl=TRUE), .)

df_A$purchased_commodity <- df_A$purchased_commodity %>% 
  factor(levels = legend_order) %>% 
  dplyr::recode(!!!legend_wrap)

material_selection = "Food Waste"
p <- plotByMaterial(df_A, material_selection, impact_vis) # ,modelname)
p
ggsave(
  gsub(" ", "", glue::glue("img/{modelname}_{impact_vis}_{material_selection}.png")),
  width = 8, height = 5)

material_selection = "Concrete"
q <- plotByMaterial(df_A, material_selection, impact_vis) #, "WARMv15")
q
ggsave(
  gsub(" ", "", glue::glue("img/{modelname}_{impact_vis}_{material_selection}.png")),
  width = 8, height = 5)
```
